[build]
  base = "FarmCure-web-app"
  publish = "."
  command = "echo 'No build command'" # No build command needed for static sites

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions" # Optional, only if you have functions
